# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96a1e33409f3f6ef5a47fce723e5fe88c9e021e845a0593560135bf628a77f9ce0072c7affdbe08936adb922ef34bf509fffc5d4add75d22ae6b75c82762414d

test:
  secret_key_base: c7dfdf12df7aa781399207d29952675c97789976ec08c457348fd2bf9cc1b177c0233b635b815ae5e245b50a05809ba7b0c6445cdd4afc651bb1b4c9c3867c58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
